services:
  bitcoin-core:
    container_name: bitcoin-core
    image: ghcr.io/joosthb/bitcoin-core-container:release
    build: .
    volumes:
      - ./data:/root/.bitcoin
      # - ./bitcoin.conf:/etc/bitcoin.conf
    ports:
      - "8333:8333"
    restart: unless-stopped
